### ISSUE TITLE
Handle make --shuffle

### ISSUE THREAD

**Issue by cbiedl** [OpenAoE/vblade#16]
Hello,
make 4.4 introduces an option "--shuffle" to make to simulate non-deterministic build order in parallel makefiles¹. Now I've learned² vblade will fail to build³. The patch provided by @hillu seems to do the trick:

```
--- a/makefile
+++ b/makefile
@@ -24,7 +24,7 @@
 ata.o : ata.c config.h dat.h fns.h makefile
        ${CC} ${CFLAGS} -c $<
 
-bpf.o : bpf.c
+bpf.o : bpf.c config.h
        ${CC} ${CFLAGS} -c $<
 
 dat.o : dat.c
@@ -38,7 +38,7 @@
        fi
 
 clean :
-       rm -f $O vblade
+       rm -f $O config.h vblade
 
 install : vblade vbladed
        install vblade ${sbindir}/
```

¹ For details, see https://trofi.github.io/posts/238-new-make-shuffle-mode.html
² https://people.debian.org/~sanvila/make-shuffle/
³ https://people.debian.org/~sanvila/make-shuffle/build-logs/vblade_25-2_amd64-20240713T085008.133Z

**Comment by ecashin** [comment]
Thank you.  Can you please create a pull request with the suggested changes?  I'm not sure it needs a version bump, though, since it's a build-process change.

**Comment by hillu** [comment]
No version bump should be needed.
